name: Deploy Bedrock Agents

on:
  push:
    branches: [main]
    paths: ['**/*.yml', '**/*.yaml']

jobs:
  deploy-dev:
    name: Deploy to Development
    runs-on: ubuntu-latest
    environment: development
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_DEPLOYMENT_ROLE }}
        aws-region: ap-southeast-2
    
    - name: Generate Terraform
      uses: chandra447/bedrock-forge@main
      with:
        command: 'generate'
        output-dir: 'outputs_tf'
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.5.0"
        
    - name: Terraform Init
      run: |
        cd outputs_tf
        terraform init \
          -backend-config="bucket=${{ secrets.TERRAFORM_STATE_BUCKET }}" \
          -backend-config="key=hr-assistant/dev/terraform.tfstate" \
          -backend-config="region=ap-southeast-2"
          
    - name: Terraform Plan
      run: |
        cd outputs_tf
        terraform plan -out=tfplan
        
    - name: Terraform Apply
      run: |
        cd outputs_tf
        terraform apply tfplan
        
    - name: Upload state
      uses: actions/upload-artifact@v4
      with:
        name: terraform-state-dev
        path: outputs_tf/terraform.tfstate
        
  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: production
    needs: deploy-dev
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_DEPLOYMENT_ROLE }}
        aws-region: ap-southeast-2
    
    - name: Generate Terraform
      uses: chandra447/bedrock-forge@main
      with:
        command: 'generate'
        output-dir: 'outputs_tf'
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.5.0"
        
    - name: Terraform Init
      run: |
        cd outputs_tf
        terraform init \
          -backend-config="bucket=${{ secrets.TERRAFORM_STATE_BUCKET }}" \
          -backend-config="key=hr-assistant/prod/terraform.tfstate" \
          -backend-config="region=ap-southeast-2"
          
    - name: Terraform Plan
      run: |
        cd outputs_tf
        terraform plan -out=tfplan
        
    - name: Terraform Apply
      run: |
        cd outputs_tf
        terraform apply tfplan
        
    - name: Upload state
      uses: actions/upload-artifact@v4
      with:
        name: terraform-state-prod
        path: outputs_tf/terraform.tfstate
