name: Validate Bedrock Configuration

on:
  pull_request:
    branches: [main]
    paths: ['**/*.yml', '**/*.yaml']

jobs:
  validate:
    name: Validate Configuration
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_VALIDATION_ROLE }}
        aws-region: ap-southeast-2
    
    - name: Checkout Bedrock Forge
      uses: actions/checkout@v4
      with:
        repository: 'chandra447/bedrock-forge'
        ref: 'main'
        path: .bedrock-forge

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build Bedrock Forge
      working-directory: .bedrock-forge
      run: |
        go build -o ../bedrock-forge ./cmd/bedrock-forge

    - name: Validate Configuration
      run: |
        ./bedrock-forge validate .
        
    - name: Generate Terraform
      run: |
        mkdir -p outputs_tf
        ./bedrock-forge generate . outputs_tf
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: terraform-plans
        path: outputs_tf/
        
    - name: Comment PR
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '✅ Bedrock configuration validation successful! Terraform files generated and ready for deployment.'
          })
